frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizReport.jsx, frontend/lqclient/src/components/QuizPage/QuizSubmitConfirmDialog.jsx
=> High Priority issue Fixes

backend/lqserver/lqserver/settings.py, frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/HomePage/NavBar.jsx, frontend/lqclient/src/components/QuizPage/QuizDescription.jsx, frontend/lqclient/src/components/QuizPage/QuizDescriptionCard.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/Utils/LoginUtils.js
#32 , #10 Signup and login fixes.
=> Signup fixes

frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/Utils/LoginUtils.js
#43 Displaying the backend errors properly now.
=> #43 Display backend error fix

frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizReport.jsx
#47 Submit answer issue fix for correct justification
=> #47 submit answer issue fix

frontend/lqclient/src/components/QuizPage/QuizReport.jsx
#49 Completed changes for showing user choice for justification
=> #49 Displaying user choice justification

frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizReport.jsx
#53 , #52  Changed the button alignments and added overview for questions in report
=> #52, #53 issue fixes

backend/lqserver/QuizBoard/lib/quiz_parser.py, backend/lqserver/QuizBoard/management/commands/add_quiz.py
=> interface for reading in quizzes

backend/lqserver/QuizBoard/admin.py, backend/lqserver/QuizBoard/api/serializers.py, backend/lqserver/QuizBoard/api/urls.py, backend/lqserver/QuizBoard/api/views.py, backend/lqserver/QuizBoard/models.py, backend/lqserver/lqserver/settings.py, frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/HomePage/NavBar.jsx, frontend/lqclient/src/components/QuizPage/QuizDescription.jsx, frontend/lqclient/src/components/QuizPage/QuizDescriptionCard.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestionCard.jsx, frontend/lqclient/src/components/QuizPage/QuizReport.jsx, frontend/lqclient/src/components/Services/AppServices.js, frontend/lqclient/src/components/Utils/LoginUtils.js
Implemented quiz report functionality and requirements mentioned in #39 and #42
=> #39, #42 fixes

.gitignore, frontend/lqclient/.env, frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/QuizPage/QuizDescription.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx
=> 15 read backend url from config

.gitignore, frontend/lqclient/.env, frontend/lqclient/package-lock.json, frontend/lqclient/package.json, frontend/lqclient/src/App.js, frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/HomePage/NavBar.jsx, frontend/lqclient/src/components/QuizPage/QuizDescription.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizSubmitConfirmDialog.jsx, frontend/lqclient/src/i18n.js, frontend/lqclient/src/index.js, frontend/lqclient/src/translations/de/common.json, frontend/lqclient/src/translations/en/common.json
fixes #11. Set up localisation using i18next
This PR is based on #63, so please review that one first
=> 11 localisation

frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx
Score calculation minor bug fix.
=> Update score minor bug fix

backend/lqserver/QuizBoard/api/views.py, backend/lqserver/lqserver/settings.py, frontend/lqclient/src/components/Authentication/Login.jsx, frontend/lqclient/src/components/Authentication/SignUp.jsx, frontend/lqclient/src/components/QuizPage/QuizDescription.jsx, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/Services/AppServices.js
#60 Added authentication with JWT token for all requests.
#71 Shows report for completed quiz.
=> #60, #71 Fixes

backend/lqserver/QuizBoard/api/serializers.py, backend/lqserver/QuizBoard/api/urls.py, backend/lqserver/QuizBoard/api/views.py, frontend/lqclient/src/components/QuizPage/QuizQuestion.jsx, frontend/lqclient/src/components/QuizPage/QuizReport.jsx, frontend/lqclient/src/components/Services/AppServices.js, frontend/lqclient/src/translations/de/common.json
=> #69 Separated Questions from answers fixes

backend/lqserver/lqserver/local_settings.py.template
=> Unset ALLOWED_HOSTS in local_settings.py.template

frontend/package.json
these are patches form the server. Does it do harm to integrate them into master? Pleas test.
=> Server patches

frontend/src/components/HighScorePage/ScoresList.jsx
Minor bug fix showing user score
=> Score list bug fix showing user score

backend/QuizBoard/api/views.py, frontend/public/index.html
#93 fixes. As quizzes are not being sorted by created date the quiz list looks outdated. Sorted the quiz list by created date. Now the new quizzes added will appear first.
=> #93 Issue fixes

backend/QuizBoard/api/views.py
Fixes #93 . added no cache headers to responses
=> #93 new changes for the cache issue fix

backend/README.md, frontend/README.md
Added the descriptions reagarding how to start applications and config files for backend and frontend.
Fixes #2
=> 2 update readme.md

frontend/src/components/QuizPage/QuizReport.jsx
fixes #103. Reroutes to available quizzes page from quiz report page if back button is clicked.
=> 103 handle routes

frontend/src/components/UserStatistics/UserScoreStatistics.jsx, frontend/src/translations/de/common.json
=> #108 fixed typo.
